sftp:
  host: "sftp.px.bylinkr.com"
  port: "8422"
  user: "linkr"
  password: "linkr2026"
  working_directory: "upload/theu"
  invoices_file: "invoices.json"
  hoinaco_file: "hoinaco.csv"
  absences_file: "mamy/Absences.csv"